{
    "name": "Advanced Domain Generator",
    "version": "15.0",
    "author": "Idealis Consulting",
    "category": "Agoria",
    "website": "http://www.idealisconsulting.com",
    "depends": ['web'],
    "data": [ ],
    'qweb': [],
    "active": False,
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
}
