{
    "name": "Advanced Domain Generator",
    "version": "1.0",
    "author": "Idealis Consulting",
    "category": "Agoria",
    "website": "http://www.idealisconsulting.com",
    "depends": ['web'],
    "data": [
        "views/web_assets.xml",
        "views/simplified_domain.xml",
        "wizard/advanced_domain_generator.xml",
        "security/ir.model.access.csv",
    ],
    'qweb': ['static/src/xml/base.xml'],
    "active": False,
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False,
}
